### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bslavin** [Automattic/php-webrisk#1]
Hi - great code examples, thank you. Is there a license that you have chosen to release this code under? We would like to use some elements. 

Thank you.

**Comment by georgestephanis** [comment]
@bslavin Sorry for the delay didn't spot the question!

GPL.

https://github.com/Automattic/php-webrisk/commit/58a2644f5118a89b584ba8c8fef4aba527fdd8e5#diff-04c6e90faac2675aa89e2176d2eec7d8

Have fun!
